# Length of chromosome
L: 1000
# Initial trait value
z: 1
# Genetic variance per unit map length
v: 1
# Number of individuals per generation
N: 1000
# Recombination rate per site
y: 5e-5
# Selection gradient
beta: 0.001
# Number of generations in the simulation
numGen: 100
# Number of replicates
num_rep: 2
# Random seed
random_seed: 1