name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.1

  Testing:
    runs-on: ubuntu-latest
    uses: snakemake/snakemake-github-action@v1.24.0
    with:
      directory: .test
      snakefile: workflow/Snakefile
      args: "--use-conda --show-failed-logs --cores 1 --conda-cleanup-pkgs cache --all-temp"